In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('california_housing_data.csv')

df[ 'income_categories'] = pd.cut( df['median_income'] , bins=[ 0 ,2 ,4, 6 , 8, np.inf],
                                                      labels=[ 1 ,2 , 3, 4, 5 ] )

In [3]:
from sklearn.model_selection import StratifiedShuffleSplit

splitting = StratifiedShuffleSplit( n_splits = 1 , test_size = 0.2 , random_state = 42)
for train_split ,  test_split in splitting.split( df , df['income_categories'] ):
    train_data = df.loc[ train_split]
    test_data = df.loc[ test_split]

train_data ,test_data

(       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 249      -122.22     37.78                44.0       1678.0           514.0
 2355     -119.68     36.77                21.0       1260.0           182.0
 11234    -117.96     33.80                30.0        729.0           131.0
 14455    -117.28     32.83                34.0       2392.0           653.0
 19071    -122.53     38.32                22.0       3577.0             NaN
 ...          ...       ...                 ...          ...             ...
 20474    -118.75     34.26                26.0       1767.0           265.0
 13975    -116.76     34.23                10.0       4374.0           989.0
 8907     -118.47     34.03                29.0       3287.0           882.0
 16805    -122.41     37.66                32.0       1385.0           356.0
 15084    -116.96     32.80                25.0       3421.0           803.0

        population  households  median_income  median_house_value  \
 249        1700.0       495.0         2.0801            131900.0
 2355        583.0       205.0         6.0132            150800.0
 11234       488.0       139.0         4.7667            195200.0
 14455       933.0       619.0         3.7306            500000.0
 19071      1371.0       501.0         5.7950            332300.0
 ...           ...         ...            ...                 ...
 20474      1040.0       250.0         5.4787            198100.0
 13975      1020.0       376.0         2.6071             89000.0
 8907       1523.0       823.0         3.7381            290600.0
 16805      1096.0       353.0         4.4750            246700.0
 15084      1681.0       742.0         3.3690            134400.0

       ocean_proximity income_categories
 249          NEAR BAY                 2
 2355           INLAND                 4
 11234       <1H OCEAN                 3
 14455      NEAR OCEAN                 2
 19071       <1H OCEAN                 3
 ...               ...               ...
 20474       <1H OCEAN                 3
 13975          INLAND                 2
 8907        <1H OCEAN                 2
 16805      NEAR OCEAN                 3
 15084       <1H OCEAN                 2

 [16512 rows x 11 columns],
        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 3700     -118.36     34.19                11.0       2921.0           685.0
 20333    -118.99     34.23                 9.0      10618.0          1617.0
 19723    -121.67     38.85                46.0        645.0           131.0
 14228    -117.04     32.68                14.0       1320.0           270.0
 11027    -117.83     33.80                31.0       2016.0           409.0
 ...          ...       ...                 ...          ...             ...
 10739    -117.92     33.57                37.0       3355.0           492.0
 11300    -117.92     33.77                28.0       3614.0           960.0
 6766     -118.13     34.10                24.0       4670.0          1185.0
 10281    -117.82     33.89                21.0       3079.0           509.0
 4768     -118.36     34.04                34.0       3239.0           806.0

        population  households  median_income  median_house_value  \
 3700       1512.0       664.0         4.1445            176400.0
 20333      4830.0      1606.0         6.6246            284200.0
 19723       410.0       122.0         1.7417            110400.0
 14228       943.0       260.0         5.0947            152700.0
 11027      1095.0       405.0         3.8681            196000.0
 ...           ...         ...            ...                 ...
 10739       921.0       366.0         7.2988            500001.0
 11300      3282.0       889.0         3.5220            190300.0
 6766       2478.0      1107.0         3.1975            252400.0
 10281      1431.0       480.0         4.0714            278900.0
 4768       2331.0       765.0         2.0538            125800.0

       ocean_proximity income_categories
 3700        <1H OCEAN                 3
 20333       <1H OCEAN                 4
 19723          INLAND                 1
 14228      NEAR OCEAN                 3
 11027       <1H OCEAN                 2
 ...               ...               ...
 10739      NEAR OCEAN                 4
 11300       <1H OCEAN                 2
 6766        <1H OCEAN                 2
 10281       <1H OCEAN                 3
 4768        <1H OCEAN                 2

 [4128 rows x 11 columns])

In [4]:

train_data.drop( columns=['income_categories'] , inplace = True)  

# inplace = True means that the changes will be made in the original dataframe and not a copy of it

test_data.drop( columns=['income_categories'] , inplace = True)

In [5]:

df = train_data.copy()

# taking a sample of 1000 data points for visualisation

In [6]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
249,-122.22,37.78,44.0,1678.0,514.0,1700.0,495.0,2.0801,131900.0,NEAR BAY
2355,-119.68,36.77,21.0,1260.0,182.0,583.0,205.0,6.0132,150800.0,INLAND
11234,-117.96,33.80,30.0,729.0,131.0,488.0,139.0,4.7667,195200.0,<1H OCEAN
14455,-117.28,32.83,34.0,2392.0,653.0,933.0,619.0,3.7306,500000.0,NEAR OCEAN
19071,-122.53,38.32,22.0,3577.0,NaN,1371.0,501.0,5.7950,332300.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
20474,-118.75,34.26,26.0,1767.0,265.0,1040.0,250.0,5.4787,198100.0,<1H OCEAN
13975,-116.76,34.23,10.0,4374.0,989.0,1020.0,376.0,2.6071,89000.0,INLAND
8907,-118.47,34.03,29.0,3287.0,882.0,1523.0,823.0,3.7381,290600.0,<1H OCEAN
16805,-122.41,37.66,32.0,1385.0,356.0,1096.0,353.0,4.4750,246700.0,NEAR OCEAN
15084,-116.96,32.80,25.0,3421.0,803.0,1681.0,742.0,3.3690,134400.0,<1H OCEAN

In [7]:

housing_features = train_data.drop( columns=['median_house_value'] , axis=1)  #  droping the label from test data

housing_label = train_data['median_house_value'].copy()  # storing the label in a separate variable

In [8]:
housing_features

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
249,-122.22,37.78,44.0,1678.0,514.0,1700.0,495.0,2.0801,NEAR BAY
2355,-119.68,36.77,21.0,1260.0,182.0,583.0,205.0,6.0132,INLAND
11234,-117.96,33.80,30.0,729.0,131.0,488.0,139.0,4.7667,<1H OCEAN
14455,-117.28,32.83,34.0,2392.0,653.0,933.0,619.0,3.7306,NEAR OCEAN
19071,-122.53,38.32,22.0,3577.0,NaN,1371.0,501.0,5.7950,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
20474,-118.75,34.26,26.0,1767.0,265.0,1040.0,250.0,5.4787,<1H OCEAN
13975,-116.76,34.23,10.0,4374.0,989.0,1020.0,376.0,2.6071,INLAND
8907,-118.47,34.03,29.0,3287.0,882.0,1523.0,823.0,3.7381,<1H OCEAN
16805,-122.41,37.66,32.0,1385.0,356.0,1096.0,353.0,4.4750,NEAR OCEAN
15084,-116.96,32.80,25.0,3421.0,803.0,1681.0,742.0,3.3690,<1H OCEAN

In [9]:
housing_label

249      131900.0
2355     150800.0
11234    195200.0
14455    500000.0
19071    332300.0
           ...
20474    198100.0
13975     89000.0
8907     290600.0
16805    246700.0
15084    134400.0
Name: median_house_value, Length: 16512, dtype: float64

========================================================================================

In [10]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer( strategy="most_frequent")  # creating an object of the class SimpleImputer -> strategy = "most_frequent" means that the missing values  imputed with int and non int data in featres col

imputer.fit( housing_features)                       # fitting the imputer object to the housing features


#----------------------------------

# imputer = SimpleImputer(strategy="median/mean")
# housing_num = housing.select_dtypes(include=[np.number])   -> only using the int data types cols from the housing features , to impute N/A val

# Note : "mean" and "median" can only be used with numerical data, but "most_frequent" can be used with both numerical and categorical data.

SimpleImputer(strategy='most_frequent')

In [11]:
# Now apply the learned most_frequent values to transform the missiing values in the housing features dataset:

X = imputer.transform(housing_features)

In [12]:
X                    # have array of final housing_features value ( imputed + already there one) ;
                     # But not in the form of dataframe, so we need to convert it into dataframe form if need to see.

array([[-122.22, 37.78, 44.0, ..., 495.0, 2.0801, 'NEAR BAY'],
       [-119.68, 36.77, 21.0, ..., 205.0, 6.0132, 'INLAND'],
       [-117.96, 33.8, 30.0, ..., 139.0, 4.7667, '<1H OCEAN'],
       ...,
       [-118.47, 34.03, 29.0, ..., 823.0, 3.7381, '<1H OCEAN'],
       [-122.41, 37.66, 32.0, ..., 353.0, 4.475, 'NEAR OCEAN'],
       [-116.96, 32.8, 25.0, ..., 742.0, 3.369, '<1H OCEAN']],
      shape=(16512, 9), dtype=object)

In [13]:

housing = pd.DataFrame(X, columns=housing_features.columns , index=housing_features.index) 
# converting the array into dataframe form and giving the column names as the 
# original housing_features column names

In [14]:

housing['ocean_proximity'] = df['ocean_proximity']

In [15]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
249,-122.22,37.78,44.0,1678.0,514.0,1700.0,495.0,2.0801,NEAR BAY
2355,-119.68,36.77,21.0,1260.0,182.0,583.0,205.0,6.0132,INLAND
11234,-117.96,33.8,30.0,729.0,131.0,488.0,139.0,4.7667,<1H OCEAN
14455,-117.28,32.83,34.0,2392.0,653.0,933.0,619.0,3.7306,NEAR OCEAN
19071,-122.53,38.32,22.0,3577.0,280.0,1371.0,501.0,5.795,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
20474,-118.75,34.26,26.0,1767.0,265.0,1040.0,250.0,5.4787,<1H OCEAN
13975,-116.76,34.23,10.0,4374.0,989.0,1020.0,376.0,2.6071,INLAND
8907,-118.47,34.03,29.0,3287.0,882.0,1523.0,823.0,3.7381,<1H OCEAN
16805,-122.41,37.66,32.0,1385.0,356.0,1096.0,353.0,4.475,NEAR OCEAN
15084,-116.96,32.8,25.0,3421.0,803.0,1681.0,742.0,3.369,<1H OCEAN

=======================================================

In [16]:
housing_cat = housing[["ocean_proximity"]]

set(housing_cat["ocean_proximity"])  # to see the unique values in the ocean_proximity column

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

-----

In [17]:
# from sklearn.preprocessing import OrdinalEncoder # string categorical data to numerical data 
#                                                   # ( A = 0 , B = 1 , C = 2 , D = 3 , E = 4 ) 

# ordinal_encode = OrdinalEncoder()

# housing_cat_ord_encoded = ordinal_encode.fit_transform(housing_cat)

# # fit_transform() method is used to fit the encoder to the 
# # data and transform the data into encoded form in one step.

In [18]:
# ordinal_encode.categories_
# # Output: array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'])

# #------

# housing_cat_ord_encoded   # numpy arr contain num data for refering catogory data

### ⚠️ Caution: Ordinal encoding implies an order between categories, which may not be true here. For example, it treats INLAND (1) as closer to <1H OCEAN (0) than NEAR OCEAN (4), which might not make sense.

------

In [19]:
from sklearn.preprocessing import OneHotEncoder  
# to convert the categorical data into multipe cols acc to no of catg contain
# [0,1] values in each col for each catg if it exist in the data or not


onehot_encoder = OneHotEncoder()

housing_cat_oh_encoded = onehot_encoder.fit_transform(housing_cat)

onehot_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [20]:
housing_cat_oh_encoded.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]], shape=(16512, 5))

In [21]:
# Convert the one-hot encoded data into a DataFrame

housing_cat_oh_encoded_df = pd.DataFrame(housing_cat_oh_encoded.toarray(), 
                                         columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'], 
                                         index=housing_features.index) 


housing_cat_oh_encoded_df

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
249          0.0     0.0     0.0       1.0         0.0
2355         0.0     1.0     0.0       0.0         0.0
11234        1.0     0.0     0.0       0.0         0.0
14455        0.0     0.0     0.0       0.0         1.0
19071        1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
20474        1.0     0.0     0.0       0.0         0.0
13975        0.0     1.0     0.0       0.0         0.0
8907         1.0     0.0     0.0       0.0         0.0
16805        0.0     0.0     0.0       0.0         1.0
15084        1.0     0.0     0.0       0.0         0.0

[16512 rows x 5 columns]

In [22]:
housing = pd.concat([housing.drop(columns=['ocean_proximity']), housing_cat_oh_encoded_df], axis=1)  
# concating the label and one hot encoded data into one dataframe


housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
249,-122.22,37.78,44.0,1678.0,514.0,1700.0,495.0,2.0801,0.0,0.0,0.0,1.0,0.0
2355,-119.68,36.77,21.0,1260.0,182.0,583.0,205.0,6.0132,0.0,1.0,0.0,0.0,0.0
11234,-117.96,33.8,30.0,729.0,131.0,488.0,139.0,4.7667,1.0,0.0,0.0,0.0,0.0
14455,-117.28,32.83,34.0,2392.0,653.0,933.0,619.0,3.7306,0.0,0.0,0.0,0.0,1.0
19071,-122.53,38.32,22.0,3577.0,280.0,1371.0,501.0,5.795,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20474,-118.75,34.26,26.0,1767.0,265.0,1040.0,250.0,5.4787,1.0,0.0,0.0,0.0,0.0
13975,-116.76,34.23,10.0,4374.0,989.0,1020.0,376.0,2.6071,0.0,1.0,0.0,0.0,0.0
8907,-118.47,34.03,29.0,3287.0,882.0,1523.0,823.0,3.7381,1.0,0.0,0.0,0.0,0.0
16805,-122.41,37.66,32.0,1385.0,356.0,1096.0,353.0,4.475,0.0,0.0,0.0,0.0,1.0
15084,-116.96,32.8,25.0,3421.0,803.0,1681.0,742.0,3.369,1.0,0.0,0.0,0.0,0.0

==========================

## Feature scaling in sklearn

Feature scaling is a crucial preprocessing step. Most machine learning algorithms perform poorly when input features have vastly different scales.

- In the California housing dataset, for example:

1. total_rooms ranges from 6 to over 39,000
2. median_income ranges from 0 to 15


If you don’t scale these features, models will give more importance to total_rooms simply because it has larger values.

### Why Scaling Is Needed
- Many models (like Linear Regression, KNN, SVMs, Gradient Descent-based algorithms) assume features are on a similar scale.
- Without scaling, features with larger ranges can dominate model behavior.
- Scaling makes training more stable and faster.

------

### 1. Min-Max Scaling (Normalization)

This method rescales the data to a specific range, usually [0, 1] or [-1, 1].

- it dont change/disrupt values , instead modulate according to the [min ,max] value.

Formula:

` scaled_value = (x - min) / (max - min)`

Use Scikit-Learn’s MinMaxScaler:

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler( feature_range=(0,1))  # scaling the data into range of 0 to 1

housing_min_max_scaled = scaler.fit_transform(housing)


housing_min_max_scaled

array([[0.21558704, 0.55685441, 0.84313725, ..., 0.        , 1.        ,
        0.        ],
       [0.47267206, 0.44952179, 0.39215686, ..., 0.        , 0.        ,
        0.        ],
       [0.64676113, 0.13390011, 0.56862745, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.5951417 , 0.15834219, 0.54901961, ..., 0.        , 0.        ,
        0.        ],
       [0.19635628, 0.54410202, 0.60784314, ..., 0.        , 0.        ,
        1.        ],
       [0.74797571, 0.02763018, 0.47058824, ..., 0.        , 0.        ,
        0.        ]], shape=(16512, 13))

In [27]:
# Convert the scaled data back into a DataFrame with the original column names and index
housing_minmax_scaled_df = pd.DataFrame(housing_min_max_scaled, 
                                        columns=housing.columns, index=housing.index)

housing_minmax_scaled_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
249,0.215587,0.556854,0.843137,0.042627,0.082474,0.104098,0.092046,0.108978,0.0,0.0,0.0,1.0,0.0
2355,0.472672,0.449522,0.392157,0.031996,0.028995,0.035578,0.037901,0.380222,0.0,1.0,0.0,0.0,0.0
11234,0.646761,0.133900,0.568627,0.018490,0.020780,0.029751,0.025579,0.294258,1.0,0.0,0.0,0.0,0.0
14455,0.715587,0.030818,0.647059,0.060786,0.104865,0.057048,0.115198,0.222804,0.0,0.0,0.0,0.0,1.0
19071,0.184211,0.614240,0.411765,0.090925,0.044781,0.083916,0.093167,0.365174,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20474,0.566802,0.182784,0.490196,0.044890,0.042365,0.063612,0.046303,0.343361,1.0,0.0,0.0,0.0,0.0
13975,0.768219,0.179596,0.176471,0.111196,0.158988,0.062385,0.069828,0.145322,0.0,1.0,0.0,0.0,0.0
8907,0.595142,0.158342,0.549020,0.083550,0.141753,0.093240,0.153286,0.223321,1.0,0.0,0.0,0.0,0.0
16805,0.196356,0.544102,0.607843,0.035175,0.057023,0.067047,0.065534,0.274141,0.0,0.0,0.0,0.0,1.0
15084,0.747976,0.027630,0.470588,0.086958,0.129027,0.102932,0.138163,0.197866,1.0,0.0,0.0,0.0,0.0

### Use feature_range=(0, 1) for models like neural networks.
### Sensitive to outliers — extreme values can distort the scale.

-------

## 2. Standardization (Z-score Scaling)

This method centers the data around 0 and scales it based on standard deviation.

Formula:

    ` standardized_value = (x - mean) / std

- Use Scikit-Learn’s StandardScaler:

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()  # scaling the data to have mean=0 and std=1

housing_std_scaled = scaler.fit_transform(housing)


housing_std_scaled

array([[-1.32209788,  1.00503914,  1.22629464, ..., -0.01740407,
         2.81435312, -0.38400979],
       [-0.05421396,  0.53188408, -0.60140225, ..., -0.01740407,
        -0.35532144, -0.38400979],
       [ 0.8043531 , -0.85947287,  0.11378349, ..., -0.01740407,
        -0.35532144, -0.38400979],
       ...,
       [ 0.54977798, -0.75172469,  0.0343184 , ..., -0.01740407,
        -0.35532144, -0.38400979],
       [-1.41693959,  0.94882269,  0.27271365, ..., -0.01740407,
        -0.35532144,  2.6041003 ],
       [ 1.30351999, -1.32794322, -0.28354192, ..., -0.01740407,
        -0.35532144, -0.38400979]], shape=(16512, 13))

In [29]:
# Convert the scaled data back into a DataFrame with the original column names and index
housing_std_scaled_df = pd.DataFrame(housing_std_scaled, 
                                     columns=housing.columns, index=housing.index)

housing_std_scaled_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
249,-1.322098,1.005039,1.226295,-0.446645,-0.055826,0.248930,-0.016487,-0.943972,-0.888665,-0.682575,-0.017404,2.814353,-0.38401
2355,-0.054214,0.531884,-0.601402,-0.639853,-0.849457,-0.771232,-0.775895,1.128352,-0.888665,1.465040,-0.017404,-0.355321,-0.38401
11234,0.804353,-0.859473,0.113783,-0.885292,-0.971371,-0.857996,-0.948726,0.471580,1.125284,-0.682575,-0.017404,-0.355321,-0.38401
14455,1.143787,-1.313889,0.431644,-0.116619,0.276448,-0.451575,0.308225,-0.074335,-0.888665,-0.682575,-0.017404,-0.355321,2.60410
19071,-1.476840,1.258013,-0.521937,0.431113,-0.615193,-0.051547,-0.000775,1.013384,1.125284,-0.682575,-0.017404,-0.355321,-0.38401
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20474,0.410011,-0.643977,-0.204077,-0.405507,-0.651049,-0.353851,-0.658056,0.846728,1.125284,-0.682575,-0.017404,-0.355321,-0.38401
13975,1.403353,-0.658031,-1.475518,0.799503,1.079641,-0.372117,-0.328106,-0.666299,-0.888665,1.465040,-0.017404,-0.355321,-0.38401
8907,0.549778,-0.751725,0.034318,0.297069,0.823862,0.087275,0.842429,-0.070383,1.125284,-0.682575,-0.017404,-0.355321,-0.38401
16805,-1.416940,0.948823,0.272714,-0.582075,-0.433518,-0.302706,-0.388335,0.317885,-0.888665,-0.682575,-0.017404,-0.355321,2.60410
15084,1.303520,-1.327943,-0.283542,0.359007,0.635016,0.231577,0.630319,-0.264859,1.125284,-0.682575,-0.017404,-0.355321,-0.38401

- Resulting features have zero mean and unit variance
- Robust to outliers compared to min-max scaling
- Recommended for most ML algorithms, especially when using gradient descent