In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('california_housing_data.csv')

df[ 'income_categories'] = pd.cut( df['median_income'] , bins=[ 0 ,2 ,4, 6 , 8, np.inf],
                                                      labels=[ 1 ,2 , 3, 4, 5 ] )

In [3]:
from sklearn.model_selection import StratifiedShuffleSplit

splitting = StratifiedShuffleSplit( n_splits = 1 , test_size = 0.2 , random_state = 42)
for train_split ,  test_split in splitting.split( df , df['income_categories'] ):
    train_data = df.loc[ train_split]
    test_data = df.loc[ test_split]

train_data ,test_data

(       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 249      -122.22     37.78                44.0       1678.0           514.0
 2355     -119.68     36.77                21.0       1260.0           182.0
 11234    -117.96     33.80                30.0        729.0           131.0
 14455    -117.28     32.83                34.0       2392.0           653.0
 19071    -122.53     38.32                22.0       3577.0             NaN
 ...          ...       ...                 ...          ...             ...
 20474    -118.75     34.26                26.0       1767.0           265.0
 13975    -116.76     34.23                10.0       4374.0           989.0
 8907     -118.47     34.03                29.0       3287.0           882.0
 16805    -122.41     37.66                32.0       1385.0           356.0
 15084    -116.96     32.80                25.0       3421.0           803.0

        population  households  median_income  median_house_value  \
 249        1700.0       495.0         2.0801            131900.0
 2355        583.0       205.0         6.0132            150800.0
 11234       488.0       139.0         4.7667            195200.0
 14455       933.0       619.0         3.7306            500000.0
 19071      1371.0       501.0         5.7950            332300.0
 ...           ...         ...            ...                 ...
 20474      1040.0       250.0         5.4787            198100.0
 13975      1020.0       376.0         2.6071             89000.0
 8907       1523.0       823.0         3.7381            290600.0
 16805      1096.0       353.0         4.4750            246700.0
 15084      1681.0       742.0         3.3690            134400.0

       ocean_proximity income_categories
 249          NEAR BAY                 2
 2355           INLAND                 4
 11234       <1H OCEAN                 3
 14455      NEAR OCEAN                 2
 19071       <1H OCEAN                 3
 ...               ...               ...
 20474       <1H OCEAN                 3
 13975          INLAND                 2
 8907        <1H OCEAN                 2
 16805      NEAR OCEAN                 3
 15084       <1H OCEAN                 2

 [16512 rows x 11 columns],
        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 3700     -118.36     34.19                11.0       2921.0           685.0
 20333    -118.99     34.23                 9.0      10618.0          1617.0
 19723    -121.67     38.85                46.0        645.0           131.0
 14228    -117.04     32.68                14.0       1320.0           270.0
 11027    -117.83     33.80                31.0       2016.0           409.0
 ...          ...       ...                 ...          ...             ...
 10739    -117.92     33.57                37.0       3355.0           492.0
 11300    -117.92     33.77                28.0       3614.0           960.0
 6766     -118.13     34.10                24.0       4670.0          1185.0
 10281    -117.82     33.89                21.0       3079.0           509.0
 4768     -118.36     34.04                34.0       3239.0           806.0

        population  households  median_income  median_house_value  \
 3700       1512.0       664.0         4.1445            176400.0
 20333      4830.0      1606.0         6.6246            284200.0
 19723       410.0       122.0         1.7417            110400.0
 14228       943.0       260.0         5.0947            152700.0
 11027      1095.0       405.0         3.8681            196000.0
 ...           ...         ...            ...                 ...
 10739       921.0       366.0         7.2988            500001.0
 11300      3282.0       889.0         3.5220            190300.0
 6766       2478.0      1107.0         3.1975            252400.0
 10281      1431.0       480.0         4.0714            278900.0
 4768       2331.0       765.0         2.0538            125800.0

       ocean_proximity income_categories
 3700        <1H OCEAN                 3
 20333       <1H OCEAN                 4
 19723          INLAND                 1
 14228      NEAR OCEAN                 3
 11027       <1H OCEAN                 2
 ...               ...               ...
 10739      NEAR OCEAN                 4
 11300       <1H OCEAN                 2
 6766        <1H OCEAN                 2
 10281       <1H OCEAN                 3
 4768        <1H OCEAN                 2

 [4128 rows x 11 columns])

In [4]:

train_data.drop( columns=['income_categories'] , inplace = True)  

# inplace = True means that the changes will be made in the original dataframe and not a copy of it

test_data.drop( columns=['income_categories'] , inplace = True)

In [5]:

df = train_data.copy()

# taking a sample of 1000 data points for visualisation

In [6]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
249,-122.22,37.78,44.0,1678.0,514.0,1700.0,495.0,2.0801,131900.0,NEAR BAY
2355,-119.68,36.77,21.0,1260.0,182.0,583.0,205.0,6.0132,150800.0,INLAND
11234,-117.96,33.80,30.0,729.0,131.0,488.0,139.0,4.7667,195200.0,<1H OCEAN
14455,-117.28,32.83,34.0,2392.0,653.0,933.0,619.0,3.7306,500000.0,NEAR OCEAN
19071,-122.53,38.32,22.0,3577.0,NaN,1371.0,501.0,5.7950,332300.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
20474,-118.75,34.26,26.0,1767.0,265.0,1040.0,250.0,5.4787,198100.0,<1H OCEAN
13975,-116.76,34.23,10.0,4374.0,989.0,1020.0,376.0,2.6071,89000.0,INLAND
8907,-118.47,34.03,29.0,3287.0,882.0,1523.0,823.0,3.7381,290600.0,<1H OCEAN
16805,-122.41,37.66,32.0,1385.0,356.0,1096.0,353.0,4.4750,246700.0,NEAR OCEAN
15084,-116.96,32.80,25.0,3421.0,803.0,1681.0,742.0,3.3690,134400.0,<1H OCEAN

In [7]:

housing_features = train_data.drop( columns=['median_house_value'] , axis=1)  #  droping the label from test data

housing_label = train_data['median_house_value'].copy()  # storing the label in a separate variable

In [8]:
housing_features

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
249,-122.22,37.78,44.0,1678.0,514.0,1700.0,495.0,2.0801,NEAR BAY
2355,-119.68,36.77,21.0,1260.0,182.0,583.0,205.0,6.0132,INLAND
11234,-117.96,33.80,30.0,729.0,131.0,488.0,139.0,4.7667,<1H OCEAN
14455,-117.28,32.83,34.0,2392.0,653.0,933.0,619.0,3.7306,NEAR OCEAN
19071,-122.53,38.32,22.0,3577.0,NaN,1371.0,501.0,5.7950,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
20474,-118.75,34.26,26.0,1767.0,265.0,1040.0,250.0,5.4787,<1H OCEAN
13975,-116.76,34.23,10.0,4374.0,989.0,1020.0,376.0,2.6071,INLAND
8907,-118.47,34.03,29.0,3287.0,882.0,1523.0,823.0,3.7381,<1H OCEAN
16805,-122.41,37.66,32.0,1385.0,356.0,1096.0,353.0,4.4750,NEAR OCEAN
15084,-116.96,32.80,25.0,3421.0,803.0,1681.0,742.0,3.3690,<1H OCEAN

In [9]:
housing_label

249      131900.0
2355     150800.0
11234    195200.0
14455    500000.0
19071    332300.0
           ...
20474    198100.0
13975     89000.0
8907     290600.0
16805    246700.0
15084    134400.0
Name: median_house_value, Length: 16512, dtype: float64

========================================================================================

### 1. SimpleImputer

In [10]:
# from sklearn.impute import SimpleImputer

# imputer = SimpleImputer( strategy="most_frequent")  # creating an object of the class SimpleImputer -> strategy = "most_frequent" means that the missing values  imputed with int and non int data in featres col

# imputer.fit( housing_features)                       # fitting the imputer object to the housing features


#----------------------------------

# imputer = SimpleImputer(strategy="median/mean")
# housing_num = housing.select_dtypes(include=[np.number])   -> only using the int data types cols from the housing features , to impute N/A val

# Note : "mean" and "median" can only be used with numerical data, but "most_frequent" can be used with both numerical and categorical data.

=======================================================

### 2. OneHotEncoder

In [11]:
# from sklearn.preprocessing import OneHotEncoder  
# # to convert the categorical data into multipe cols acc to no of catg contain
# # [0,1] values in each col for each catg if it exist in the data or not


# onehot_encoder = OneHotEncoder()

# housing_cat_oh_encoded = onehot_encoder.fit_transform(housing_cat)

# onehot_encoder.categories_

==========================

### 3. MinMaxScaler

In [12]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler( feature_range=(0,1))  # scaling the data into range of 0 to 1

# housing_min_max_scaled = scaler.fit_transform(housing)


# housing_min_max_scaled

----

# Pipelines in sklearn

As datasets grow more complex, data preprocessing often involves multiple steps such as imputing missing values, scaling features, encoding categorical variables, etc. These steps must be applied in the correct order and consistently across training, validation, test, and future production data.

To streamline this process, Scikit-Learn provides the Pipeline class — a powerful utility for chaining data transformations.

=============================================================

### 1. Building a Numerical Pipeline
A typical pipeline for numerical attributes might include:

1. Imputation of missing values (e.g., with median).
2. Feature scaling (e.g., with standardization).

In [13]:
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


my_pipeline = Pipeline([
    
            ('imputer' , SimpleImputer(strategy="median")),
            ('scaler' , StandardScaler())
             
             # ( 'step_name' , Transformer/Estimator Object )  
                        ])

======================================================================

### 2. Applying the Pipeline

Call fit_transform() to apply all transformations in sequence:

In [14]:
housing_nums = housing_features.drop(columns=['ocean_proximity'] , axis=1)

In [15]:
housing_num_prepared = my_pipeline.fit_transform(housing_nums)

# give me numpy array after applying all steps in pipeline

Example output:

       ` array([[-1.42,  1.01,  1.86,  0.31,  1.37,  0.14,  1.39, -0.94],
       ` [ 0.60, -0.70,  0.91, -0.31, -0.44, -0.69, -0.37,  1.17]])
       
- Each row corresponds to a transformed sample.
- Each column corresponds to a scaled feature.

In [16]:
# Retrieving Feature Names
# To turn the result back into a DataFrame with feature names:

df_housing_num_prepared = pd.DataFrame(
    housing_num_prepared,
    columns=my_pipeline.get_feature_names_out(),
    index=housing_nums.index
)


df_housing_num_prepared

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
249,-1.322098,1.005039,1.226295,-0.446645,-0.059694,0.248930,-0.016487,-0.943972
2355,-0.054214,0.531884,-0.601402,-0.639853,-0.854618,-0.771232,-0.775895,1.128352
11234,0.804353,-0.859473,0.113783,-0.885292,-0.976730,-0.857996,-0.948726,0.471580
14455,1.143787,-1.313889,0.431644,-0.116619,0.273120,-0.451575,0.308225,-0.074335
19071,-1.476840,1.258013,-0.521937,0.431113,-0.246454,-0.051547,-0.000775,1.013384
...,...,...,...,...,...,...,...,...
20474,0.410011,-0.643977,-0.204077,-0.405507,-0.655887,-0.353851,-0.658056,0.846728
13975,1.403353,-0.658031,-1.475518,0.799503,1.077621,-0.372117,-0.328106,-0.666299
8907,0.549778,-0.751725,0.034318,0.297069,0.821426,0.087275,0.842429,-0.070383
16805,-1.416940,0.948823,0.272714,-0.582075,-0.438001,-0.302706,-0.388335,0.317885
15084,1.303520,-1.327943,-0.283542,0.359007,0.632272,0.231577,0.630319,-0.264859

=================================================================

### 3. How It Works

- The pipeline takes a list of steps as (name, transformer) pairs.
- Names must be unique and should not contain double underscores __.
- All intermediate steps must be transformers (i.e., must implement fit_transform()).
- The final step can be either a transformer or a predictor.

==========

#### Using make_pipeline

- If you don't want to name the steps manually, you can use make_pipeline():

In [17]:

from sklearn.pipeline import make_pipeline    # no name is required for transformer/predicter operation

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer


num_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    StandardScaler()
    )


# => This automatically names the steps using the class names in lowercase.

# => If the same class appears multiple times, a number is appended (e.g., standardscaler-1).

----------

--------

## Pipeline as a Transformer or Predictor

 1. If the last step is a transformer, the pipeline behaves like a transformer (fit_transform(), transform()).

 2. If the last step is a predictor (e.g., a model), the pipeline behaves like an estimator (fit(), predict()).

#####  This flexibility makes Pipeline the standard way to handle data preprocessing and modeling in Scikit-Learn projects.